/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hw
 */
public class Customer_CreditBalance extends javax.swing.JFrame {
    private String user;
    /**
     * Creates new form Customer_CreditBalance
     */
    public Customer_CreditBalance(String user) {
        setTitle("Customer Transaction");
        initComponents();
        this.user="CUSTOMER1";
        try {
            showcreditBalance();
            showtransaction();
        } catch (IOException ex) {
            Logger.getLogger(Customer_CreditBalance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCreditBalance = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLTransaction = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(675, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(675, 500));

        lbCreditBalance.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbCreditBalance.setForeground(new java.awt.Color(102, 102, 102));
        lbCreditBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCreditBalance.setText("CREDIT BALANCE");

        lblCreditBalance.setBackground(new java.awt.Color(204, 204, 204));
        lblCreditBalance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCreditBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreditBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCreditBalance.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCreditBalanceAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Transaction History:");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //btnBackActionPerformed(evt);
            	new Customer_Homepage(user);
            	dispose();
            }
        });

        TBLTransaction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TBLTransaction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TBLTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "TRANSACTION", "CREDIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TBLTransaction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lbCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(3, 3, 3)
                .addComponent(lbCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreditBalanceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCreditBalanceAncestorAdded
        
    }//GEN-LAST:event_lblCreditBalanceAncestorAdded

    /*private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Customer_Homepage home= new Customer_Homepage(user);
        home.show();
        dispose();
    }*///GEN-LAST:event_btnBackActionPerformed
// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public void showcreditBalance() throws IOException {
        String creditfile = "customer.txt";

        FileReader fr = new FileReader(creditfile);
        BufferedReader br = new BufferedReader(fr);

        String creditline; 
        while((creditline = br.readLine())!=null){
            String[] orderpart = creditline.split(":");
            if (orderpart.length == 3 && user.equals(orderpart[0])) {
                String credit = orderpart[2];
                lblCreditBalance.setText("RM"+credit);
            }
        } 
    } 

    public void showtransaction() throws FileNotFoundException, IOException{
        String transactionfile = "CustomerTransaction.txt";
        File tf = new File(transactionfile);
        FileReader fr = new FileReader(tf);
        BufferedReader br = new BufferedReader(fr);
        
        DefaultTableModel tranmodel = (DefaultTableModel)TBLTransaction.getModel();
        
        String tranline; 
        while((tranline = br.readLine())!=null){
            String[] tranpart = tranline.split(":");
            if (tranpart.length == 4 && user.equals(tranpart[0])) {
                String date = tranpart[1];
                String transaction = tranpart[2];
                String pricededucted = tranpart[3];
                
                tranmodel.addRow(new Object[]{date, transaction, pricededucted});
            }
        } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLTransaction;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCreditBalance;
    private javax.swing.JLabel lblCreditBalance;
    // End of variables declaration//GEN-END:variables
}
