/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hw
 */
public class Customer_Review extends javax.swing.JFrame {
    private String user;
    String reviewFile=("OrderReview.txt");
    File rf=new File(reviewFile);
    /**
     * Creates new form Customer_Review
     */
    public Customer_Review(String user) throws IOException {
        setTitle("Review");
        initComponents();
        this.user=user;
        try {
            viewReview();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Customer_Review.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLReview = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("FOOD REVIEW");

        TBLReview.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TBLReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER", "DATE", "ORDER ID", "VENDOR", "REVIEW"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLReview);
        if (TBLReview.getColumnModel().getColumnCount() > 0) {
            TBLReview.getColumnModel().getColumn(0).setMinWidth(110);
            TBLReview.getColumnModel().getColumn(0).setMaxWidth(110);
            TBLReview.getColumnModel().getColumn(1).setMinWidth(90);
            TBLReview.getColumnModel().getColumn(1).setMaxWidth(90);
            TBLReview.getColumnModel().getColumn(2).setMinWidth(90);
            TBLReview.getColumnModel().getColumn(2).setMaxWidth(90);
            TBLReview.getColumnModel().getColumn(3).setMinWidth(90);
            TBLReview.getColumnModel().getColumn(3).setMaxWidth(90);
        }

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Customer_Homepage home = new Customer_Homepage(user);
        home.show();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void viewReview() throws FileNotFoundException, IOException{
        FileReader rfr=new FileReader(rf);
        BufferedReader bfr=new BufferedReader(rfr);
        DefaultTableModel reviewmodel = (DefaultTableModel)TBLReview.getModel();
        
        String reviewline;
        while ((reviewline = bfr.readLine()) != null) {
                String[] reviewpart = reviewline.split(":");
                if (reviewpart.length == 5) {
                    String customer=reviewpart[0];
                    String date = reviewpart[1];
                    String orderid = reviewpart[2];
                    String vendor = reviewpart[3];
                    String review = reviewpart[4];
                    
                    reviewmodel.addRow(new Object[]{customer,date, orderid,vendor, review});
                }
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLReview;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
