
import javax.swing.JOptionPane;

public class DR_Menu extends javax.swing.JFrame {
    private String location;
    private String userid;
    public DR_Menu(String userid) {   
        setTitle("Delivery Runner");
        this.userid = userid;
        initComponents();
        txtRunner.setText(userid);
    }
        public DR_Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAvail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOngo = new javax.swing.JButton();
        btnTask = new javax.swing.JButton();
        btnReview = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        txtRunner = new javax.swing.JTextField();
        txtNofi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));
        setVisible(true);

        btnAvail.setText("Available task");
        btnAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailActionPerformed(evt);
            }
        });

        jLabel1.setText("Delivery Runner: ");

        btnOngo.setText("Ongoing task");
        btnOngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOngoActionPerformed(evt);
            }
        });

        btnTask.setText("Task history");
        btnTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskActionPerformed(evt);
            }
        });

        btnReview.setText("Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });

        btnRevenue.setText("Revenue");
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        txtRunner.setEditable(false);

        txtNofi.setText("Notification");
        txtNofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNofiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNofi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTask, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOngo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRunner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNofi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOngo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTask, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnLogOut)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailActionPerformed
        location = "available";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_btnAvailActionPerformed

    private void btnTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskActionPerformed
        location = "history";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_btnTaskActionPerformed

    private void btnOngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOngoActionPerformed
        location = "ongoing";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_btnOngoActionPerformed

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        location = "revenue";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_btnRevenueActionPerformed

    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        location = "review";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_btnReviewActionPerformed

    private void txtNofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNofiActionPerformed
        location = "nofi";
        Redirect(location);
        this.dispose();
    }//GEN-LAST:event_txtNofiActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int confirmLogout = JOptionPane.showConfirmDialog(null ,"Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	if (confirmLogout == JOptionPane.YES_OPTION)
	{
            LoginView view = new LoginView();
            LoginController controller = new LoginController(view);
            controller.startApplication();
            this.dispose();
	}
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */

    
    public void Redirect(String form){
        if("available".equals(form)){
            DR_AvailableTask obj = new DR_AvailableTask(userid);
            obj.setVisible(true);
        }
        else if("history".equals(form)){
            DR_History obj = new DR_History(userid);
            obj.setVisible(true);
        }
        else if("ongoing".equals(form)){
            DR_Ongoing obj = new DR_Ongoing(userid);
            obj.setVisible(true);
        }
        else if("revenue".equals(form)){
            DR_Revenue obj = new DR_Revenue(userid);
            obj.setVisible(true);
        }
        else if("review".equals(form)){
            DR_Review obj = new DR_Review(userid);
            obj.setVisible(true);
        }
        else if("menu".equals(form)){
            DR_Menu obj = new DR_Menu(userid);
            obj.setVisible(true);
        }
        else if("nofi".equals(form)){
            Notifications obj = new Notifications(userid);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvail;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOngo;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JButton btnReview;
    private javax.swing.JButton btnTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtNofi;
    private javax.swing.JTextField txtRunner;
    // End of variables declaration//GEN-END:variables
}
