/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 *
 * @author wongx
 */
public class MainMenuVendorForm extends javax.swing.JFrame {

    private String vendorname;

    public MainMenuVendorForm(String vendorname) {
        setVisible(true);
        setTitle("Vendor");
        initComponents();
        this.vendorname = vendorname;
        lvendor.setText(String.valueOf(vendorname));
    }

    
    public MainMenuVendorForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bHistory = new javax.swing.JButton();
        bRevenue = new javax.swing.JButton();
        bMenu = new javax.swing.JButton();
        bOrder = new javax.swing.JButton();
        bReview = new javax.swing.JButton();
        bnotification = new javax.swing.JButton();
        lwelcome = new javax.swing.JLabel();
        lvendor = new javax.swing.JLabel();
        blogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bHistory.setText("Order History");
        bHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoryActionPerformed(evt);
            }
        });

        bRevenue.setText("Revenue");
        bRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevenueActionPerformed(evt);
            }
        });

        bMenu.setText("Menu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        bOrder.setText("Order Form");
        bOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrderActionPerformed(evt);
            }
        });

        bReview.setText("Review");
        bReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReviewActionPerformed(evt);
            }
        });

        bnotification.setText("Show Notification");
        bnotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnotificationActionPerformed(evt);
            }
        });

        lwelcome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lwelcome.setText("Welcome:");

        blogout.setText("Log Out");
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lvendor, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bReview, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnotification)
                    .addComponent(blogout))
                .addGap(29, 29, 29))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        // TODO add your handling code here:
        MenuVendor vf = new MenuVendor(vendorname);
        vf.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_bMenuActionPerformed

    private void bRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevenueActionPerformed
        RevenueForm vf = new RevenueForm(vendorname);
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRevenueActionPerformed

    private void bOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrderActionPerformed
        OrderForm vf = new OrderForm(vendorname);
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bOrderActionPerformed

    private void bReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReviewActionPerformed
        // TODO add your handling code here:
        
        ReviewForm vf = new ReviewForm(vendorname);
        vf.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bReviewActionPerformed

    private void bHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoryActionPerformed
        // TODO add your handling code here:
        HistoryForm vf = new HistoryForm(vendorname);
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bHistoryActionPerformed

    private void bnotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnotificationActionPerformed
        Notifications nt = new Notifications(vendorname);
    }//GEN-LAST:event_bnotificationActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
    int confirmLogout = JOptionPane.showConfirmDialog(null ,"Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	if (confirmLogout == JOptionPane.YES_OPTION)
	{
            LoginView view = new LoginView();
            LoginController controller = new LoginController(view);
            controller.startApplication();
            dispose();
	}
    }//GEN-LAST:event_blogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHistory;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bOrder;
    private javax.swing.JButton bRevenue;
    private javax.swing.JButton bReview;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bnotification;
    private javax.swing.JLabel lvendor;
    private javax.swing.JLabel lwelcome;
    // End of variables declaration//GEN-END:variables
}
