/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wongx
 */
public class ReviewForm extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private String[] columName = {"Date","Order ID","Comments"};
    
    private String date;
    private String orderid;
    private String vendorname;
    private String comments;
    
    private String filepath = "OrderReview.txt";
    
    
    public ReviewForm(String vendorname) {
        setVisible(true);
        setTitle("Customer review");
        this.vendorname = vendorname;
        initComponents();
        model.setColumnIdentifiers(columName);
        TableReview.setEnabled(false);
        lvendorname.setText(vendorname);
        insertData();    
    }
    
    
    /**
     * Creates new form ReviewForm
     */
    public ReviewForm() {
        initComponents();
        model.setColumnIdentifiers(columName);
        TableReview.setEnabled(false);
        lvendorname.setText(vendorname);
        insertData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableReview = new javax.swing.JTable();
        brefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lvendorname = new javax.swing.JLabel();
        breturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableReview.setModel(model);
        jScrollPane1.setViewportView(TableReview);

        brefresh.setText("Refresh");
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });

        jLabel1.setText("Vendor:");

        lvendorname.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lvendorname.setPreferredSize(new java.awt.Dimension(100, 100));

        breturn.setText("Return to Main Page");
        breturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lvendorname, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(brefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(breturn))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(breturn)))
                .addGap(18, 18, 18)
                .addComponent(lvendorname, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(brefresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        // TODO add your handling code here:\
        //ReviewClass rc = new ReviewClass(vendorname);
        clearTable();
        insertData();
    }//GEN-LAST:event_brefreshActionPerformed

    private void breturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breturnActionPerformed
        MainMenuVendorForm vf = new MainMenuVendorForm(vendorname);
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_breturnActionPerformed


    
    private void insertData(){
    String[] values = {date, orderid, vendorname, comments};
    try {
        FileReader fr = new FileReader(filepath);
        BufferedReader br = new BufferedReader(fr);
        String line;
        while ((line = br.readLine()) != null) {
            String[] split_line = line.split(":");
            for (int i = 3; i < split_line.length; i = i + 3) {
                
                //System.out.println("splitline1: " + split_line[i]);
                //System.out.println("vendorname: " + vendorname);

                if (split_line[i].equals(vendorname)) {
                    //System.out.println("splitline2"+split_line[i].trim());
                    values[i] = split_line[i].trim();
                    model.addRow(split_line);    

                    //System.out.println("yes");
                }


                //System.out.println("values[i]: " + values[i]);
                
            }
        }
        br.close();
    } catch (IOException e) {
        System.err.println("An error occurred while reading the file: " + e.getMessage());
    }
    }
    

    
    private void clearTable() {
        // Clear all rows from the table model
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableReview;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton breturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvendorname;
    // End of variables declaration//GEN-END:variables
}
